plugins:
    checkstyle:
        enabled: true
        config:
            file: "tools/checkstyle.xml"
    fixme:
        enabled: true
    markdownlint:
        enabled: true
    pmd:
        enabled: true
    sonar-java:
        enabled: true
        config:
            sonar.java.source: 8
            test_patterns:
                - src/test/java/**

