language: java
jdk:
- openjdk8
notifications:
  email: false
script:
- mvn clean compile
- mvn test || echo "There were failed tests"

before_deploy:
- mvn package

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: lOL56wXx2nexa9XEj6Zfz3SdAoDkNcUSA3f9MJQtbn2okF6+uRpz6iGUlJWqoN6EmqmiTSlgFeYt2U7F014t2rklvO7kmzY4sHfqgvNEpgd48Q2viNS1Xer7wEaE0YLSz2+MBzL1CireoiWXS9UvadW0jy/wjhX0p9w5O4xdI/23pK28evFW4hCNQwAS38hO1ehzOV4djIuadR9isxhXh63XRtM1KaXrCAqsqKitx10UQpq/T7/mYKzD8zr24gu3r4yoPCjEFqxftmK6tT5EJm/rjDeyC8DFoH8+SbMpK9vmSVXuKQEiYDVgjL0ij/zH/OsXJLN4sMCcvs60H56My1ePdzH/jmrsMnX4F/dn+V/CsoIiO5z3pFjRWXm+za1aXGdoZ7TGDvUQoaJ1D9fXvRuisIXKQjC6hHSei4aBDWbqEJzMk3VK5Hh9dz2yO+s7Bp1XOA3hgaKCOvakue95Jq8bHnhQ2dsYQsDO+FpSbuPw93FeDagJq6ombGspDXYdHE+4Jaq967Nz4SSpFJ99W92a9ehed3c3HQ6WjtTQEno04zpVRr+qdwzUahec/3jOfALD0l52ici+D6dbwdgt8fPq3XIMUdIQPTH+CvXJdzhCIODqQe3NaY0FipAodN7NJdFz+NQSycmJIQo6rIGHQLO8xQBiQmANCDZWNoyYf8s=
  file_glob: true
  file: target/*.jar
  on:
    tags: true
    repo: joshchamberlain/CS471-Assignments-UMLIntro-GitHubTest2
