language: java
jdk:
- openjdk8
notifications:
  email: false
env:
  global:
  - CC_TEST_REPORTER_ID=5362b49f61c8d7fc3e953d9fd9685eabc3d60b06598dd4d16761ac0b88518b08
  - secure: e4bHNfFlUqBB/FRZpeXm72W3D0dQnoP8ko9jPv7DjwrMLV8mE80ThzOZmXRwBiJQtVgXWt1ZOziFoHgtoQbqyNWdLp8rSPhmONx0wIDhe7UZKAhigqQju6mwqmnc0Grz9vbaFcpEpfe7UqUQvVmcHrpgMXYouj1gjUi4p5JLSj3OiE/bbNkXs2gsnruCQsN68MsmjMRTVHvlI8PXIQiJnVcEbT8ZoCDABoKiaIZw/A2EIhik9tqQWT/n3fEoYu96hYfr9ICU5tt4qTcnKvfocaN6s+x2s/nb1eqWqrUL65FTDyYFhi3ZdNQoTsAqZuRdPe335vbTT5oZSEh44suwmoYosuz8v+FyAYxD1RH9RgElnNs3LQXCMjcOOsjIXWfHnBzp1FxQxmGwRtnUyr3WH2KHx5qra4IXjWPL3nMF21eGecYLsLEBg64eL0w8ee3WAhdPWOl5yB6Q0Nr4NkYVsmSXo2ZLaL/M+mNLfrSeAGrh5gRldFWVe3i8IjEba2LWHbTukNcnaOK5FJKd+A6f775YNTGhKEuEys6UeV59FUzfkboIsZwYPmdxKePtc5Lfr91VIXzuNQDf8Rb7ByFaKmH7sd+vYXcdzuBDroXkuX+7b4KoNVUoBGFo+75aJI3gsCTFwuSh4XvrObFLwkWHHFNSuHrlKpRYFuuywHzjiuM=

jobs:
  include:
    - stage: compile
      script:
          - mvn clean compile
    - stage: tests
      script:
          - ./releng/travis/pre-test
          - ./releng/travis/test
          - ./releng/travis/post-test
    - stage: validate_pull_request
      name: "Checkstyle"
      script: 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then mvn checkstyle:check; fi'
    - # Same stage
      name: "Test Coverage"
      script: 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then mvn verify -P pullrequest; fi'
cache:
  directories:
    - $HOME/.m2    
    - $HOME/.sonar/cache
